### ISSUE TITLE
Full data request

### ISSUE THREAD

**Issue by gulinan** [FrisovanDijk/bibliometric-network-analysis#1]
Hi,
Thanks for this nice work. I would like to use this example for my class. I wonder whether you can also share the full data so that we can get the network analysis from scratch. Thanks a lot.

**Comment by FrisovanDijk** [comment]
Hi, thank you very much. I would love to share the dataset more broadly, but the Elsevier license explicitly restricts this:

> Retention of original research dataset is limited to archival purposes and reproduction of the research results. Data use outside of the scope of the original research is not permitted.

The best I can do is share my approach, tools and outcomes. A few people in my research group have played around with this method as well, and they managed to get data and start analysis in an afternoon. If you have Scopus access, I think that is your best option. Though the larger the intended dataset, the more the API limits will slow you down. Sorry I cannot be of more help than that.

**Comment by gulinan** [comment]
Thank you. Your suggestions are great!..Then, I would do so.
